sudo: false
os: linux
dist: trusty
language: php

php:
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

services:
- mysql

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

before_install:
- mysql < ./tests/Fixture/db.sql
- mysql -e "SET PASSWORD = PASSWORD('password');"

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit
- php eloquent-generator generate --config-file=tests/Fixture/database.php

before_deploy:
- make

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
  - composer.phar
