sudo: false
os: linux
dist: trusty
language: php

php:
- 7.1
- 7.2
- nightly

matrix:
  global:
    DOCKER_IMAGE: 104corp/eloquent-generator
  allow_failures:
  - php: nightly

services:
- mysql
- postgresql

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

env:
  global:
    POSTGRES_USERNAME: travis

before_install:
# Prepare MySQL schema
- mysql < ./tests/Fixture/mysql.sql
- mysql -e "SET PASSWORD = PASSWORD('password');"
# Prepare Sqlite schema
- sqlite3 tests/Fixture/sqlite.db < tests/Fixture/sqlite.sql
# Prepare postgresql
- psql -U postgres -d postgres -f tests/Fixture/postgres.sql

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit --coverage-clover=coverage.xml
- php eloquent-generator --config-file=tests/Fixture/database.php

after_success:
- if [ "7.1" == "${TRAVIS_PHP_VERSION}" ]; then bash <(curl -s https://codecov.io/bash) ; fi
- |
  if [ "7.1" == "${TRAVIS_PHP_VERSION}" && "false" == "${TRAVIS_PULL_REQUEST}" ]; then
    docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
    docker push ${DOCKER_IMAGE}
  fi

before_deploy:
- make

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
  - composer.phar

deploy:
  provider: releases
  api_key:
    secure: LwGRgw9rYapw/9Tes+pSueIbSuzITvlG86bB8fCz+aasfFiylYxbgulSPd5MpwNqTUUSHYsgi4fqIYA34v4UatljJHwkAV+sYVSZ68FIjALR8wWTyhKZRfXJ4/0FFjIKzSTiPLz7yM0GN2zhoPTNtt7gyJky4B9zMBEtv8CbD0UwmoXZrBC9mSmbUOrOL/6qYX9W/74oAUWHP0cMtb4+CsDz5vpSdqMeTXGYT8SUpqMFWF9bROG7xc5KYsdDjlu5EtzEIeWmuQgFGaqudthYWPzj0wGDCqDbrHi0y3To0t6PquHZE+8TW4RMPbOUjbChGTvATobACYlEBLCoaWmjgM/HxhwlkIZvU2hO9qMnD/A5xXEj4hQDDiOJpsF8iVU5c4q4/MfD7NBARUEZW0Sxa1Tt7mpHBPRJNvNw7WxCgJoD6GCoFa9gbbWBLjb9hiUdKXNCsJjN54L2jsjS1GCoBcTMod5OVHGEn8zV1AzYeRoPA1+3XrMmVOJqqJkzqwEJPq/XUC9+CgWr9wyWHnnAd3dzPRDGU0+BQaOtQAvNLHVa/GAAucloTVViEBVyPZxpTXA8OoPL5VrwVJvXJtdumbIQSSRMsct0yxHVghbNutimz+cJgOmX5fAWs29C8S3EJ/tZxR2K2ETnwEbWlpQoymKCjUt2sO2+MwbuUUhc0lg=
  file: eloquent-generator.phar
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
