sudo: false
os: linux
dist: trusty
language: php

php:
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

services:
- mysql
- postgresql

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

env:
  global:
    POSTGRES_USERNAME: travis

before_install:
# Prepare MySQL schema
- mysql < ./tests/Fixture/mysql.sql
- mysql -e "SET PASSWORD = PASSWORD('password');"
# Prepare Sqlite schema
- sqlite3 tests/Fixture/sqlite.db < tests/Fixture/sqlite.sql
# Prepare postgresql
- psql -U postgres -d postgres -f tests/Fixture/postgres.sql


install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit
- php eloquent-generator --config-file=tests/Fixture/database.php

before_deploy:
- make

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
  - composer.phar
