version: "2.1"
services:
  mysql:
    image: percona:5.6
    container_name: mysql
    hostname: mysql
    volumes:
    - ./tests/Fixture/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  postgres:
    image: postgres:10-alpine
    container_name: postgres
    hostname: postgres
    volumes:
    - ./tests/Fixture/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
