version: "2.1"
services:
  mysql:
    image: percona:5.6
    container_name: mysql
    hostname: mysql
    volumes:
    - ./tests/Fixture:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: password
